export const pieceImages = {
  King: "king.png",
  Bishop: "bishop.png",
  Gold: "gold.png",
  Silver: "silver.png",
  Lance: "lance.png",
  Knight: "knight.png",
  Rook: "rook.png",
  Pawn: "pawn.png",
  PromotedKing: "promoted_king.png",
  PromotedBishop: "promoted_bishop.png",
  PromotedGold: "promoted_gold.png",
  PromotedSilver: "promoted_silver.png",
  PromotedLance: "promoted_lance.png",
  PromotedKnight: "promoted_knight.png",
  PromotedRook: "promoted_rook.png",
  PromotedPawn: "promoted_pawn.png",
};

export const board = [
  [
    { piece: "Lance", player: 2 },
    { piece: "Knight", player: 2 },
    { piece: "Silver", player: 2 },
    { piece: "Gold", player: 2 },
    { piece: "King", player: 2 },
    { piece: "Gold", player: 2 },
    { piece: "Silver", player: 2 },
    { piece: "Knight", player: 2 },
    { piece: "Lance", player: 2 },
  ],
  [
    { piece: "", player: null },
    { piece: "Rook", player: 2 },
    { piece: "", player: null },
    { piece: "", player: null },
    { piece: "", player: null },
    { piece: "", player: null },
    { piece: "", player: null },
    { piece: "Bishop", player: 2 },
    { piece: "", player: null },
  ],
  [
    { piece: "Pawn", player: 2 },
    { piece: "Pawn", player: 2 },
    { piece: "Pawn", player: 2 },
    { piece: "Pawn", player: 2 },
    { piece: "Pawn", player: 2 },
    { piece: "Pawn", player: 2 },
    { piece: "Pawn", player: 2 },
    { piece: "Pawn", player: 2 },
    { piece: "Pawn", player: 2 },
  ],
  [
    { piece: "", player: null },
    { piece: "", player: null },
    { piece: "", player: null },
    { piece: "", player: null },
    { piece: "", player: null },
    { piece: "", player: null },
    { piece: "", player: null },
    { piece: "", player: null },
    { piece: "", player: null },
  ],
  [
    { piece: "", player: null },
    { piece: "", player: null },
    { piece: "", player: null },
    { piece: "", player: null },
    { piece: "", player: null },
    { piece: "", player: null },
    { piece: "", player: null },
    { piece: "", player: null },
    { piece: "", player: null },
  ],
  [
    { piece: "", player: null },
    { piece: "", player: null },
    { piece: "", player: null },
    { piece: "", player: null },
    { piece: "", player: null },
    { piece: "", player: null },
    { piece: "", player: null },
    { piece: "", player: null },
    { piece: "", player: null },
  ],
  [
    { piece: "Pawn", player: 1 },
    { piece: "Pawn", player: 1 },
    { piece: "Pawn", player: 1 },
    { piece: "Pawn", player: 1 },
    { piece: "Pawn", player: 1 },
    { piece: "Pawn", player: 1 },
    { piece: "Pawn", player: 1 },
    { piece: "Pawn", player: 1 },
    { piece: "Pawn", player: 1 },
  ],
  [
    { piece: "", player: null },
    { piece: "Bishop", player: 1 },
    { piece: "", player: null },
    { piece: "", player: null },
    { piece: "", player: null },
    { piece: "", player: null },
    { piece: "", player: null },
    { piece: "Rook", player: 1 },
    { piece: "", player: null },
  ],
  [
    { piece: "Lance", player: 1 },
    { piece: "Knight", player: 1 },
    { piece: "Silver", player: 1 },
    { piece: "Gold", player: 1 },
    { piece: "King", player: 1 },
    { piece: "Gold", player: 1 },
    { piece: "Silver", player: 1 },
    { piece: "Knight", player: 1 },
    { piece: "Lance", player: 1 },
  ],
];

export const movingOptions = {
  King: [
    [0, 1],
    [0, -1],
    [-1, 1],
    [-1, 0],
    [-1, -1],
    [1, -1],
    [1, 0],
    [1, 1],
  ],

  PromotedKing: [
    [0, 1],
    [0, -1],
    [-1, 1],
    [-1, 0],
    [-1, -1],
    [1, -1],
    [1, 0],
    [1, 1],
  ],

  Gold: [
    [0, 1],
    [0, -1],
    [-1, 1],
    [-1, 0],
    [-1, -1],
    [1, 0],
  ],

  Silver: [
    [-1, 1],
    [-1, 0],
    [-1, -1],
    [1, -1],
    [1, 1],
  ],

  Knight: [
    [-2, -1],
    [-2, 1],
  ],

  Pawn: [[-1, 0]],

  PromotedRook: [
    [-1, -1],
    [-1, 1],
    [1, -1],
    [1, 1],
  ],

  PromotedBishop: [
    [-1, 0],
    [1, 0],
    [0, -1],
    [0, 1],
  ],
};
